### ISSUE TITLE
@Metered not working on Spring MVC Controller

### ISSUE THREAD

**Issue by bertramn** [ryantenney/metrics-spring#153] opened 2015-11-12 00:44 UTC
Hi there,

I tried to add `@Metered` to a Spring MVC Controller but do not get any metrics. I read the section about Spring AOP limitations but not sure if this the problem in this case.

My Spring configuration below and the annotations I added to the controller method. Is there any other configuration or annotations required to make this work?

```xml
<metrics:metric-registry id="metrics" />
<metrics:health-check-registry id="healthCheck" />

<metrics:annotation-driven metric-registry="metrics" health-check-registry="healthCheck" />

<metrics:reporter type="slf4j" metric-registry="metrics" period="1m" />

<metrics:register metric-registry="metrics">
  <bean metrics:name="jvm.gc" class="com.codahale.metrics.jvm.GarbageCollectorMetricSet" />
  <bean metrics:name="jvm.memory" class="com.codahale.metrics.jvm.MemoryUsageGaugeSet" />
</metrics:register>
```

and my MVC Controller is annotated like this:

```java
@Controller
public class BlaController {

	@Timed
	@Counted
        @Metered
	@ResponseBody
	@RequestMapping(value = "bla", method = RequestMethod.POST, produces = APPLICATION_JSON_VALUE, consumes = APPLICATION_JSON_VALUE)
	public SomeResponse bla(@RequestBody Request request) {
      // do something I want to measure
	}

}
```

Many thanks for pointers. Niels

**Comment by ryantenney** [comment] 2015-11-13 19:03
I've encountered this issue before, your Spring WebApplicationContext is treated as a subcontext, so you need to add a `<metrics:annotation-driven />` to its context config.

My web.xml looks like this:
```xml
	<context-param>
		<param-name>contextConfigLocation</param-name>
		<param-value>
			classpath:spring/applicationContext.xml
		</param-value>
	</context-param>

	<listener>
		<listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
	</listener>

	<servlet>
		<servlet-name>api-v1-dispatcher</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
		<init-param>
			<param-name>contextConfigLocation</param-name>
			<param-value>classpath:spring/api-v1-dispatcher-servlet.xml</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>

	<servlet-mapping>
		<servlet-name>api-v1-dispatcher</servlet-name>
		<url-pattern>/api/v1/*</url-pattern>
	</servlet-mapping>
```

So both applicationContext.xml and api-v1-dispatcher-servlet.xml contain `<metrics:annotation-driven />`.

Hope that helps!

**Comment by bertramn** [comment] 2015-11-14 04:08
Thanks a million, I did have indeed a subcontext in my web application. Adding the `<metrics:annotation-driven />` element to the dispatcher context did the trick. Do you think it would be worth adding a little note about this to the README? Somethign like below:

If your spring application uses nested spring contexts and each context loads classes annotated with metrics annotations, add the `<metrics:annotation-driven />` directive to each spring context configuration. This will ensure all metrics annotated classes are registered for metrics collection. A typical example is a spring mvc web application. You may configure the metrics registry and reporters in the main web application context whilst metered controllers are defined in the dispatch servlet context.

the application wide context file `applicationContext.xml` contains the metrics setup and may also load metered services:
```xml
<beans>
  <!-- application wide metrics configuration -->
  <metrics:metric-registry id="metrics" />
  <metrics:annotation-driven metric-registry="fancy-metrics" />
  <metrics:reporter type="slf4j" metric-registry="fancy-metrics" period="1m" />
  <!-- metered services here --->
</beans>
```
and in the dispatcher servlet specific context file `api-v1-dispatcher-servlet.xml` repeat the annotation driven configuration:
```xml
<beans>
  <!-- ensures that all controllers in this subcontext are registered -->
  <metrics:annotation-driven metric-registry="fancy-metrics" />
  <!-- metered controllers here --->
</beans>
```

**Comment by joakimhop** [comment] 2016-01-07 13:24
I had a similar issue. This saved my day!

**Comment by romanwozniak** [comment] 2016-03-24 15:34
Hi. I have a similar issue, but I'm using annotation-based configuration. 
So, I defined metrics in application context using `@EnableMetrics` annotation, but the problem is that `@Timed, @Metered etc.` annotations don't work in MVC controllers (which are under servlet context, child of application context).

When I try to duplicate `@EnableMetrics` in servlet context configuration, another instance of `MetricRegistry` is created and metric data are stored to different registries. 
Thanks for any help.

**Comment by ryantenney** [comment] 2016-03-24 17:34
Ah yes. I don't know what I can do to prevent this issue, but in the meantime you can work around it by implementing the method `MetricRegistry getMetricRegistry()` from the interface `MetricsConfigurer` in both `@EnableMetrics` annotated classes, e.g.:

```java
@EnableMetrics
@Configuration
public class SpringMetricsConfigurer implements MetricConfigurer {
    public MetricRegistry getMetricRegistry() {
        return SharedMetricRegistries.getOrCreate("YOUR_SHARED_REGISTRY_NAME");
    }
}
```

**Comment by ryantenney** [comment] 2016-03-24 17:35
Closing as the original issue is resolved.

**Closed by ryantenney** 2016-03-24 17:35 UTC

**Comment by dancingmad** [comment] 2017-06-20 12:43
seems that it is not possible to use spring boot actuator and metrics spring at the same time, since both are trying to auto create the registry, ending up having two of them
